language: rust
before_install:
  - sudo add-apt-repository ppa:team-xbmc/ppa -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install libsdl2-dev libXxf86vm-dev
script:
  - cargo test -v
  - cargo doc -v
