[package]
name = "piston2d-glium_graphics"
version = "0.24.0"
authors = [
    "Eduard Bopp <eduard.bopp@aepsil0n.de>",
    "bvssvni <bvssvni@gmail.com>"
]
keywords = ["graphics", "2d", "glium", "piston"]
description = "A Glium 2D back-end for the Piston game engine"
license = "MIT"
repository = "https://github.com/PistonDevelopers/glium_graphics.git"
homepage = "https://github.com/PistonDevelopers/glium_graphics"


[lib]
name = "glium_graphics"


[dependencies.glium]
version = "0.14.0"
default_features = false

[dependencies]
freetype-rs = "0.7.0"
image = "0.9.0"
piston-shaders_graphics2d = "0.1.0"
piston2d-graphics = "0.16.0"
piston-texture = "0.4.0"
piston = "0.22.0"
shader_version = "0.2.0"
pistoncore-glutin_window = "0.26.0"
