[package]
name = "glium_graphics"
version = "0.0.4"
authors = [
    "Eduard Bopp <eduard.bopp@aepsil0n.de>",
    "bvssvni <bvssvni@gmail.com>"
]

[dependencies]
image = "0.3"

[dev-dependencies]
glutin = "0.0.22"

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs"
#version = "0.0.8"

[dependencies.piston2d-graphics]
git = "https://github.com/PistonDevelopers/graphics"
#version = "0.0.27"

[dependencies.shader_version]
git = "https://github.com/PistonDevelopers/shader_version"
#version = "0.0.6"

[dependencies.glium]
version = "0.2"
features = ["image", "gl_read_buffer"]
default_features = false
