[package]
name = "piston2d-glium_graphics"
version = "0.3.0"
authors = [
    "Eduard Bopp <eduard.bopp@aepsil0n.de>",
    "bvssvni <bvssvni@gmail.com>"
]
keywords = ["graphics", "2d", "glium", "piston"]
description = "A Glium 2D back-end for the Piston game engine"
license = "MIT"
repository = "https://github.com/PistonDevelopers/glium_graphics.git"
homepage = "https://github.com/PistonDevelopers/glium_graphics"


[lib]
name = "glium_graphics"


[dependencies.glium]
version = "0.8"
features = ["image"]
default_features = false

[dependencies]
freetype-rs = "0.2.1"
image = "0.3.11"
piston-shaders_graphics2d = "0.1.0"
piston2d-graphics = "0.4.1"
pistoncore-window = "0.8.0"
shader_version = "0.2.0"

[dev-dependencies]
piston = "0.9.0"
pistoncore-glutin_window = "0.11.0"
