[package]
name = "glium_graphics"
version = "0.0.4"
authors = [
    "Eduard Bopp <eduard.bopp@aepsil0n.de>",
    "bvssvni <bvssvni@gmail.com>"
]

[dependencies]
image = "*"

[dev-dependencies]
glutin = "*"

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs"

[dependencies.piston2d-graphics]
git = "https://github.com/PistonDevelopers/graphics"

[dependencies.shader_version]
git = "https://github.com/PistonDevelopers/shader_version"

[dependencies.glium]
features = ["image", "gl_read_buffer"]
default_features = false
