[package]
name = "glium_graphics"
version = "0.0.4"
authors = [
    "Eduard Bopp <eduard.bopp@aepsil0n.de>",
    "bvssvni <bvssvni@gmail.com>"
]
keywords = ["graphics", "2d", "glium", "piston"]
description = "A Glium 2D back-end for the Piston game engine"
license = "MIT"
repository = "https://github.com/PistonDevelopers/glium_graphics.git"
homepage = "https://github.com/PistonDevelopers/glium_graphics"

[dependencies]
image = "0.3"

[dev-dependencies]
glutin = "0.0"

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs"
#version = "0.0.8"

[dependencies.piston2d-graphics]
git = "https://github.com/PistonDevelopers/graphics"
#version = "0.0.27"

[dependencies.shader_version]
git = "https://github.com/PistonDevelopers/shader_version"
#version = "0.0.6"

[dependencies.pistoncore-window]
git = "https://github.com/PistonDevelopers/window"

[dependencies.glium]
version = "0.2"
features = ["image"]
default_features = false
